tap "buo/cask-upgrade"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "khanhas/tap"
tap "romkatv/powerlevel10k"
# Distributed revision control system
brew "git"
# Mac App Store command-line interface
brew "mas"
# Cryptography and SSL/TLS Toolkit
brew "openssl@3"
# Library for command-line editing
brew "readline"
# Python version management
brew "pyenv"
# Command-line interface for SQLite
brew "sqlite"
# General-purpose data compression with high compression ratio
brew "xz"
# Tool Command Language
brew "tcl-tk"
# Programmatically correct mistyped console commands
brew "thefuck"
# Display directories as trees (with optional color/HTML output)
brew "tree"
# Internet file retriever
brew "wget"
# General-purpose lossless data-compression library
brew "zlib"
# UNIX shell (command interpreter)
brew "zsh"
# Fish-like fast/unobtrusive autosuggestions for zsh
brew "zsh-autosuggestions"
# Fish shell like syntax highlighting for zsh
brew "zsh-syntax-highlighting"
# Command-line tool to customize Spotify client
brew "khanhas/tap/spicetify-cli"
# A Zsh Theme
brew "romkatv/powerlevel10k/powerlevel10k"
# Password manager that keeps all passwords secure behind one password
cask "1password"
# Command-line helper for the 1Password password manager
cask "1password-cli"
# Application launcher and productivity software
cask "alfred"
# Application uninstaller
cask "appcleaner"
# Voice and text chat software
cask "discord"
# Tool to hide status bar icons
cask "dozer"
# Web browser
cask "firefox"
# Typeface made for developers
cask "font-jetbrains-mono"
cask "font-source-code-pro"
# Terminal emulator as alternative to Apple's Terminal app
cask "iterm2"
# Provides updates to various Microsoft products
cask "microsoft-auto-update"
# Office suite
cask "microsoft-office"
# Calculator and converter application
cask "numi"
# Move and resize windows using keyboard shortcuts or snap areas
cask "rectangle"
# Tool that provides consistent, highly configurable symbols for apps
cask "sf-symbols"
# Music streaming service
cask "spotify"
# Text editor for code, markup and prose
cask "sublime-text"
# Open-source code editor
cask "visual-studio-code"
mas "1Password for Safari", id: 1569813296
mas "GoodNotes", id: 1444383602
mas "Xcode", id: 497799835
